name    'cloudfile'
version '1.0.0'
source  'https://github.com/cloudability/cloudfile'
author  'Carl Hall'
license 'MIT License'
summary 'Puppet module to retrieve files from a cloud provider'
description 'Puppet module to retrieve files from a cloud provider'
project_page 'https://github.com/cloudability/cloudfile'
